kind: Job
apiVersion: batch/v1
metadata:
    name: jobexample
spec:
    template:
        spec:
            containers:
            -   name: jobcontainers
                image: docker/whalesay
                command: ["cowsay","hello"]
            restartPolicy:  Never
    backoffLimit: 4
    activeDeadlineSeconds: 60
