kind: Service
apiVersion: v1
metadata:
    name: my-service
    labels:
      for: abc-pod
      type: frontend
    annotations:
      createdBy: ibtihaj
      email: ibtihajnaeem1@gmail.com
    namespace: kubepractice
spec:
    ports:
    -   port: 80
        targetPort: 80
    type: LoadBalancer
    selector:
        app: rsexample