kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: pvc
    namespace: kubepractice
spec:
    accessModes:
    -   ReadWriteOnce
    resources:
        requests:
            storage: 100M
    storageClassName: ""
